package life.qbic.portal.sampletracking.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import life.qbic.portal.sampletracking.components.projectoverview.ProjectDesign;
import life.qbic.portal.sampletracking.components.projectoverview.ProjectView;
import life.qbic.portal.sampletracking.components.sampleoverview.SampleDesign;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import life.qbic.portal.sampletracking.components.sampleoverview.SampleView;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainPage extends VerticalLayout {
    protected HorizontalLayout hotbar;
    protected HorizontalLayout toggleButtonLayout;
    protected Button projectView;
    protected Button sampleView;

    public MainPage(ProjectView projectLayout, SampleView sampleLayout) {
        Design.read(this);


        this.addComponents(projectLayout,sampleLayout);
        sampleLayout.setVisible(false);
    }
}
