qube_version: '2.6.1 # <<QUBE_NO_BUMP>>'
full_name: Jennifer Bödker
email: jennifer.boedker@qbic.uni-tuebingen.de
project_name: Sample Tracking Status Overview
project_short_description: Gives a visual overview of sample statuses
version: 1.0.0-SNAPSHOT
domain: portlet
language: groovy
project_slug: Sample_Tracking_Status_Overview
project_slug_no_hyphen: Sample_Tracking_Status_Overview
template_version: '1.0.4 # <<QUBE_NO_BUMP>>'
template_handle: portlet-groovy
github_username: jenniferboedker
creator_github_username: jenniferboedker
is_github_repo: true
is_repo_private: false
is_github_orga: false
copyright_holder: QBiC
license: MIT
main_class_prefix: Qbic
use_openbis_client: no
use_openbis_raw_api: no
use_qbic_databases: yes
use_vaadin_charts: yes
