package life.qbic.portal.sampletracking.view.samples;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import life.qbic.datamodel.samples.Status;
/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
public class SampleDesign extends VerticalLayout {
    protected HorizontalLayout hotbarLayout;
    protected TextField searchField;
    protected ComboBox<Status> statusComboBox;
    protected Button projectsButton;
    protected Button samplesButton;

    public SampleDesign() {
        Design.read(this);
    }

}
